version: "3"

services:
  backapp:
    image: kanap/vacancy-analyzer
    container_name: vacancy-analyzer
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - 8081:8081
    depends_on:
      - selenium-hub
    volumes:
      - ./src/main/resources:/src/main/resources
    networks:
      - backend

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 9000:9000
    depends_on:
      - backapp
    networks:
      - backend

  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

networks:
  backend:
    driver: "bridge"
