#Server settings
server:
  port: 8081

###
# Spring settings
###
spring:
  application:
    name: vacancyanalyzer
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  #H2 enabled console
  h2:
    console:
      enabled: true
  #Email sender settings
  mail:
    host: smtp.gmail.com
    username: mailsendertelegram@gmail.com
    password: kuszoulyjsjuccuo
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
