#Server settings
server:
  port: 8081

###
# Spring settings
###
spring:
  application:
    name: vacancyanalyzer
  codec:
    max-in-memory-size: 10MB
  #Jpa settings
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  #H2 enabled console
  h2:
    console:
      enabled: true
  #Email sender settings
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  statsd:
    metrics:
      export:
        enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
