apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://host.docker.internal:9090
    orgId: 1
    basicAuth: true
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
